### ISSUE TITLE
How to do it on Replit.com?

### ISSUE THREAD

**Issue by Vaibhav-Naik-26** [ALTER869993/Discord-Account-Creator-2022#5]
How to do it on replit.com

**Comment by ALTER869993** [comment]
You cant

**Comment by Vaibhav-Naik-26** [comment]
tell me all the steps how to use it on windows 10
i don't know anything

**Comment by ALTER869993** [comment]
Dm me on discord

**Comment by Rokasrrr** [comment]
what is ur discord?

**Comment by Rokasrrr** [comment]
ur discord plz?

**Comment by IRONMAN8599** [comment]
Alter sabse bada chutiya#0001

**Comment by Vaibhav-Naik-26** [comment]
This doesn't works , stop putting wrong things
