### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by irtco2** [ALTER869993/Discord-Account-Creator-2022#7]

**Comment by ALTER869993** [comment]
Explain how is it a virus under 24 hours or I block you in this repo

**Comment by irtco2** [comment]
the file whose name is "hcapbypasser.exe" my windows security says its a virus

**Comment by ALTER869993** [comment]
Windows will detect most of the files which aren't signed 
And you have to pay Microsoft to get your .exe file signed 
You can always remove the file from the gen but it won't solve captchas without it

**Comment by irtco2** [comment]
ok I am sorry for that

**Comment by ALTER869993** [comment]
No worries mate have a good day :D
